# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslink',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='post',
            name='startups',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='tags',
        ),
        migrations.DeleteModel(
            name='NewsLink',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Startup',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
